// "Most likely to..." prompts. Read aloud; on the count of three everyone points
// at who fits best. Kept kind and silly, never mean. Each is tagged with a theme
// pack, and a few cheeky ones are flagged so the "Keep it gentle" toggle can hide
// them. British spellings throughout.

import type { PromptEntry } from "@/games/shared";

// Theme packs offered in Setup. Keep in sync with the `pack` values below.
export const MLT_PACKS = [
  { value: "everyday", label: "Everyday & family" },
  { value: "adventure", label: "Adventure & dreams" },
  { value: "silly", label: "Silly & cheeky" },
];

export const MOST_LIKELY_TO: PromptEntry[] = [
  { text: "Most likely to become famous", pack: "everyday" },
  { text: "Most likely to sleep through their alarm", pack: "silly" },
  { text: "Most likely to become a YouTuber", pack: "everyday" },
  { text: "Most likely to trip over their own feet", pack: "silly" },
  { text: "Most likely to win a dance-off", pack: "silly" },
  { text: "Most likely to laugh at the wrong moment", pack: "silly" },
  { text: "Most likely to forget where they put something", pack: "everyday" },
  { text: "Most likely to eat the last biscuit", pack: "silly" },
  { text: "Most likely to become a famous chef", pack: "everyday" },
  { text: "Most likely to talk to animals", pack: "adventure" },
  { text: "Most likely to survive a zombie apocalypse", pack: "adventure" },
  { text: "Most likely to win a staring contest", pack: "silly" },
  { text: "Most likely to go to space one day", pack: "adventure" },
  { text: "Most likely to start singing out of nowhere", pack: "silly" },
  { text: "Most likely to get lost in a supermarket", pack: "silly" },
  { text: "Most likely to invent something amazing", pack: "adventure" },
  { text: "Most likely to cry at a sad film", pack: "everyday" },
  { text: "Most likely to be late to their own party", pack: "silly" },
  { text: "Most likely to adopt ten pets", pack: "silly" },
  { text: "Most likely to become a teacher", pack: "everyday" },
  { text: "Most likely to win a quiz", pack: "everyday" },
  { text: "Most likely to fall asleep first at a sleepover", pack: "silly" },
  { text: "Most likely to do a silly dance in public", pack: "silly" },
  { text: "Most likely to break the high score", pack: "everyday" },
  { text: "Most likely to make everyone laugh", pack: "silly" },
  { text: "Most likely to forget someone's name", pack: "everyday" },
  { text: "Most likely to become a superhero", pack: "adventure" },
  { text: "Most likely to eat something weird for a dare", pack: "silly" },
  { text: "Most likely to spend all their pocket money at once", pack: "silly" },
  { text: "Most likely to climb the tallest tree", pack: "adventure" },
  { text: "Most likely to win an award", pack: "everyday" },
  { text: "Most likely to get scared at a scary film", pack: "silly" },
  { text: "Most likely to know all the words to a song", pack: "everyday" },
  { text: "Most likely to become a famous artist", pack: "everyday" },
  { text: "Most likely to be a great leader", pack: "everyday" },
  { text: "Most likely to wear odd socks", pack: "silly" },
  { text: "Most likely to talk in their sleep", pack: "silly" },
  { text: "Most likely to become a scientist", pack: "everyday" },
  { text: "Most likely to start a food fight", pack: "silly" },
  { text: "Most likely to be the loudest in the room", pack: "silly" },
  { text: "Most likely to give the best presents", pack: "everyday" },
  { text: "Most likely to go on a big adventure", pack: "adventure" },
  { text: "Most likely to keep a secret", pack: "everyday" },
  { text: "Most likely to win a race", pack: "everyday" },
  { text: "Most likely to tell the best jokes", pack: "silly" },
  { text: "Most likely to become a movie star", pack: "everyday" },
  { text: "Most likely to help a stranger", pack: "everyday" },
  { text: "Most likely to build the best sandcastle", pack: "everyday" },
  { text: "Most likely to get the giggles in assembly", pack: "silly" },
  { text: "Most likely to have the messiest room", pack: "silly" },
  {
    text: "Most likely to become a famous explorer and discover a hidden island",
    pack: "adventure",
  },
  { text: "Most likely to befriend every dog in the neighbourhood", pack: "silly" },
  { text: "Most likely to wear wellies in the middle of summer", pack: "silly" },
  { text: "Most likely to build a fort out of sofa cushions", pack: "silly" },
  {
    text: "Most likely to start a conversation with a complete stranger on the bus",
    pack: "silly",
  },
  { text: "Most likely to grow the wonkiest vegetables in the garden", pack: "silly" },
  { text: "Most likely to become an astronaut and name a star after Nan", pack: "adventure" },
  { text: "Most likely to put ketchup on absolutely everything", pack: "silly" },
  { text: "Most likely to learn to juggle in a single afternoon", pack: "silly" },
  { text: "Most likely to organise the family holiday down to the last minute", pack: "everyday" },
  { text: "Most likely to rescue a worm from a puddle after it rains", pack: "silly" },
  { text: "Most likely to invent a brand-new flavour of crisp", pack: "silly" },
  { text: "Most likely to fall asleep in the car before they leave the driveway", pack: "silly" },
  { text: "Most likely to become a champion welly-wanging thrower", pack: "silly" },
  { text: "Most likely to collect the most conkers in autumn", pack: "silly" },
  { text: "Most likely to learn an instrument just to play one silly tune", pack: "silly" },
  { text: "Most likely to volunteer to help wash up before being asked", pack: "everyday" },
  { text: "Most likely to name every plant in the house", pack: "silly" },
  { text: "Most likely to get a round of applause for a brilliant cartwheel", pack: "silly" },
  { text: "Most likely to bring home a stray hedgehog", pack: "silly" },
  { text: "Most likely to become a brilliant magician at family parties", pack: "silly" },
  { text: "Most likely to wear sunglasses indoors and pretend it's normal", pack: "silly" },
  { text: "Most likely to build a robot out of cardboard boxes", pack: "adventure" },
  { text: "Most likely to read a whole book under the covers with a torch", pack: "everyday" },
  { text: "Most likely to befriend the postman and learn his life story", pack: "silly" },
  { text: "Most likely to win the egg-and-spoon race at sports day", pack: "everyday" },
  { text: "Most likely to start a band in the garden shed", pack: "adventure" },
  { text: "Most likely to remember everyone's birthday without being reminded", pack: "everyday" },
  { text: "Most likely to put on a puppet show for the whole family", pack: "silly" },
  { text: "Most likely to become a brilliant pilot one day", pack: "adventure" },
  { text: "Most likely to do a happy dance when the dinner arrives", pack: "silly" },
  { text: "Most likely to keep a diary full of secret adventures", pack: "adventure" },
  { text: "Most likely to spot a shooting star before anyone else", pack: "everyday" },
  { text: "Most likely to plan an elaborate treasure hunt around the house", pack: "adventure" },
  { text: "Most likely to talk during the entire film and ask what's happening", pack: "silly" },
  { text: "Most likely to build the biggest snowman in the street", pack: "everyday" },
  { text: "Most likely to bring snacks for everyone on a long journey", pack: "everyday" },
  { text: "Most likely to become a famous wildlife presenter on telly", pack: "adventure" },
  { text: "Most likely to win a game of hide-and-seek by hiding for hours", pack: "silly" },
  { text: "Most likely to learn a card trick and show it a hundred times", pack: "silly" },
  { text: "Most likely to grow up to run their own little café", pack: "everyday" },
  { text: "Most likely to cheer the loudest at a football match", pack: "silly" },
  { text: "Most likely to make friends with every cat they meet", pack: "silly" },
  { text: "Most likely to become a brilliant inventor of useless gadgets", pack: "silly" },
  { text: "Most likely to pack three jumpers for a sunny day out", pack: "silly" },
  { text: "Most likely to win first prize at the village fete", pack: "everyday" },
  { text: "Most likely to start humming the theme tune to everything", pack: "silly" },
  { text: "Most likely to build a den in the garden and live there all summer", pack: "adventure" },
  { text: "Most likely to become a coastguard or lifeboat hero", pack: "adventure" },
  { text: "Most likely to give a name to the family car", pack: "silly" },
  { text: "Most likely to do an impression of every relative at the table", pack: "silly" },
  { text: "Most likely to become a champion paper-aeroplane folder", pack: "silly" },
  { text: "Most likely to save up for years to buy something brilliant", pack: "everyday" },
  { text: "Most likely to learn to bake the most enormous cake", pack: "everyday" },
  { text: "Most likely to become a brilliant football referee", pack: "everyday" },
  { text: "Most likely to talk to the telly during a quiz show", pack: "silly" },
  { text: "Most likely to write a story about the whole family", pack: "everyday" },
  { text: "Most likely to become a famous gardener with their own show", pack: "everyday" },
  { text: "Most likely to wear fancy dress on an ordinary Tuesday", pack: "silly" },
  { text: "Most likely to become a brilliant firefighter", pack: "adventure" },
  { text: "Most likely to make up their own secret handshake", pack: "silly" },
  { text: "Most likely to spend an hour choosing which biscuit to have", pack: "silly" },
  { text: "Most likely to become a champion at board games", pack: "everyday" },
  { text: "Most likely to plant a tree and visit it every year", pack: "everyday" },
  { text: "Most likely to befriend a robin in the garden", pack: "silly" },
  { text: "Most likely to become a brilliant train driver", pack: "adventure" },
  { text: "Most likely to turn the living room into an obstacle course", pack: "adventure" },
  { text: "Most likely to learn to whistle a whole song", pack: "silly" },
  { text: "Most likely to become the family photographer at every event", pack: "everyday" },

  // Cheeky-but-gentle — hidden while "Keep it gentle" is on.
  { text: "Most likely to blame a smell on the dog", pack: "silly", cheeky: true },
  { text: "Most likely to laugh so hard they snort", pack: "silly", cheeky: true },
  { text: "Most likely to do the loudest burp at the table", pack: "silly", cheeky: true },
  { text: "Most likely to get caught picking their nose", pack: "silly", cheeky: true },
  { text: "Most likely to fall asleep and dribble on the sofa", pack: "silly", cheeky: true },
  {
    text: "Most likely to trump in a quiet room and blame someone else",
    pack: "silly",
    cheeky: true,
  },
];
