// Family-friendly "Most likely to..." prompts. Read aloud; on the count of three
// everyone points at who fits best. Kept kind and silly, never mean.

export const MOST_LIKELY_TO: string[] = [
  "Most likely to become famous",
  "Most likely to sleep through their alarm",
  "Most likely to become a YouTuber",
  "Most likely to trip over their own feet",
  "Most likely to win a dance-off",
  "Most likely to laugh at the wrong moment",
  "Most likely to forget where they put something",
  "Most likely to eat the last biscuit",
  "Most likely to become a famous chef",
  "Most likely to talk to animals",
  "Most likely to survive a zombie apocalypse",
  "Most likely to win a staring contest",
  "Most likely to go to space one day",
  "Most likely to start singing out of nowhere",
  "Most likely to get lost in a supermarket",
  "Most likely to invent something amazing",
  "Most likely to cry at a sad film",
  "Most likely to be late to their own party",
  "Most likely to adopt ten pets",
  "Most likely to become a teacher",
  "Most likely to win a quiz",
  "Most likely to fall asleep first at a sleepover",
  "Most likely to do a silly dance in public",
  "Most likely to break the high score",
  "Most likely to make everyone laugh",
  "Most likely to forget someone's name",
  "Most likely to become a superhero",
  "Most likely to eat something weird for a dare",
  "Most likely to spend all their pocket money at once",
  "Most likely to climb the tallest tree",
  "Most likely to win an award",
  "Most likely to get scared at a scary film",
  "Most likely to know all the words to a song",
  "Most likely to become a famous artist",
  "Most likely to be a great leader",
  "Most likely to wear odd socks",
  "Most likely to talk in their sleep",
  "Most likely to become a scientist",
  "Most likely to start a food fight",
  "Most likely to be the loudest in the room",
  "Most likely to give the best presents",
  "Most likely to go on a big adventure",
  "Most likely to keep a secret",
  "Most likely to win a race",
  "Most likely to tell the best jokes",
  "Most likely to become a movie star",
  "Most likely to help a stranger",
  "Most likely to build the best sandcastle",
  "Most likely to get the giggles in assembly",
  "Most likely to have the messiest room",
  "Most likely to become a famous explorer and discover a hidden island",
  "Most likely to befriend every dog in the neighbourhood",
  "Most likely to wear wellies in the middle of summer",
  "Most likely to build a fort out of sofa cushions",
  "Most likely to start a conversation with a complete stranger on the bus",
  "Most likely to grow the wonkiest vegetables in the garden",
  "Most likely to become an astronaut and name a star after Nan",
  "Most likely to put ketchup on absolutely everything",
  "Most likely to learn to juggle in a single afternoon",
  "Most likely to organise the family holiday down to the last minute",
  "Most likely to rescue a worm from a puddle after it rains",
  "Most likely to invent a brand-new flavour of crisp",
  "Most likely to fall asleep in the car before they leave the driveway",
  "Most likely to become a champion welly-wanging thrower",
  "Most likely to collect the most conkers in autumn",
  "Most likely to learn an instrument just to play one silly tune",
  "Most likely to volunteer to help wash up before being asked",
  "Most likely to name every plant in the house",
  "Most likely to get a round of applause for a brilliant cartwheel",
  "Most likely to bring home a stray hedgehog",
  "Most likely to become a brilliant magician at family parties",
  "Most likely to wear sunglasses indoors and pretend it's normal",
  "Most likely to build a robot out of cardboard boxes",
  "Most likely to read a whole book under the covers with a torch",
  "Most likely to befriend the postman and learn his life story",
  "Most likely to win the egg-and-spoon race at sports day",
  "Most likely to start a band in the garden shed",
  "Most likely to remember everyone's birthday without being reminded",
  "Most likely to put on a puppet show for the whole family",
  "Most likely to become a brilliant pilot one day",
  "Most likely to do a happy dance when the dinner arrives",
  "Most likely to keep a diary full of secret adventures",
  "Most likely to spot a shooting star before anyone else",
  "Most likely to plan an elaborate treasure hunt around the house",
  "Most likely to talk during the entire film and ask what's happening",
  "Most likely to build the biggest snowman in the street",
  "Most likely to bring snacks for everyone on a long journey",
  "Most likely to become a famous wildlife presenter on telly",
  "Most likely to win a game of hide-and-seek by hiding for hours",
  "Most likely to learn a card trick and show it a hundred times",
  "Most likely to grow up to run their own little café",
  "Most likely to cheer the loudest at a football match",
  "Most likely to make friends with every cat they meet",
  "Most likely to become a brilliant inventor of useless gadgets",
  "Most likely to pack three jumpers for a sunny day out",
  "Most likely to win first prize at the village fete",
  "Most likely to start humming the theme tune to everything",
  "Most likely to build a den in the garden and live there all summer",
  "Most likely to become a coastguard or lifeboat hero",
  "Most likely to give a name to the family car",
  "Most likely to do an impression of every relative at the table",
  "Most likely to become a champion paper-aeroplane folder",
  "Most likely to save up for years to buy something brilliant",
  "Most likely to learn to bake the most enormous cake",
  "Most likely to become a brilliant football referee",
  "Most likely to talk to the telly during a quiz show",
  "Most likely to write a story about the whole family",
  "Most likely to become a famous gardener with their own show",
  "Most likely to wear fancy dress on an ordinary Tuesday",
  "Most likely to become a brilliant firefighter",
  "Most likely to make up their own secret handshake",
  "Most likely to spend an hour choosing which biscuit to have",
  "Most likely to become a champion at board games",
  "Most likely to plant a tree and visit it every year",
  "Most likely to befriend a robin in the garden",
  "Most likely to become a brilliant train driver",
  "Most likely to turn the living room into an obstacle course",
  "Most likely to learn to whistle a whole song",
  "Most likely to become the family photographer at every event",
];
