// Built-in categorized words for Impostor. Plain data — add a category or more
// words by editing this list. Categories double as the optional impostor hint.

export interface WordCategory {
  category: string;
  words: string[];
}

export const WORD_BANK: WordCategory[] = [
  {
    category: "Food",
    words: [
      "Pizza",
      "Sushi",
      "Pancake",
      "Burger",
      "Spaghetti",
      "Taco",
      "Ice cream",
      "Chocolate",
      "Popcorn",
      "Sandwich",
      "Dumpling",
      "Waffle",
      "Cheese",
      "Donut",
      "Curry",
      "Pretzel",
      "Lasagna",
      "Omelette",
      "Croissant",
      "Soup",
    ],
  },
  {
    category: "Animals",
    words: [
      "Elephant",
      "Penguin",
      "Dolphin",
      "Kangaroo",
      "Octopus",
      "Giraffe",
      "Hedgehog",
      "Crocodile",
      "Squirrel",
      "Flamingo",
      "Panda",
      "Owl",
      "Koala",
      "Cheetah",
      "Hippo",
      "Chameleon",
      "Walrus",
      "Raccoon",
      "Peacock",
      "Sloth",
    ],
  },
  {
    category: "Places",
    words: [
      "Beach",
      "Library",
      "Airport",
      "Hospital",
      "Museum",
      "Castle",
      "Volcano",
      "Desert",
      "Cinema",
      "Stadium",
      "Lighthouse",
      "Waterfall",
      "Subway",
      "Bakery",
      "Zoo",
      "Aquarium",
      "Campsite",
      "Playground",
      "Farm",
      "Cave",
    ],
  },
  {
    category: "Movies & Shows",
    words: [
      "Titanic",
      "Frozen",
      "Jaws",
      "Avatar",
      "Shrek",
      "Gladiator",
      "Up",
      "Matrix",
      "Inception",
      "Toy Story",
      "Jurassic Park",
      "Star Wars",
      "Coco",
      "The Lion King",
      "Harry Potter",
      "Spider-Man",
      "Encanto",
      "Moana",
      "Cars",
      "Ratatouille",
    ],
  },
  {
    category: "Sports",
    words: [
      "Football",
      "Tennis",
      "Swimming",
      "Boxing",
      "Cycling",
      "Surfing",
      "Skiing",
      "Basketball",
      "Archery",
      "Bowling",
      "Karate",
      "Climbing",
      "Hockey",
      "Golf",
      "Volleyball",
      "Skating",
      "Diving",
      "Rowing",
      "Fencing",
      "Gymnastics",
    ],
  },
  {
    category: "Household",
    words: [
      "Toaster",
      "Pillow",
      "Umbrella",
      "Mirror",
      "Candle",
      "Blanket",
      "Kettle",
      "Scissors",
      "Vacuum",
      "Doorbell",
      "Toothbrush",
      "Lamp",
      "Fridge",
      "Clock",
      "Broom",
      "Remote",
      "Bucket",
      "Hairdryer",
      "Stapler",
      "Ladder",
    ],
  },
  {
    category: "Jobs",
    words: [
      "Firefighter",
      "Astronaut",
      "Chef",
      "Teacher",
      "Pilot",
      "Doctor",
      "Farmer",
      "Magician",
      "Plumber",
      "Detective",
      "Lifeguard",
      "Barber",
      "Sailor",
      "Artist",
      "Dentist",
      "Mechanic",
      "Gardener",
      "Librarian",
      "Photographer",
      "Clown",
    ],
  },
  {
    category: "Nature",
    words: [
      "Rainbow",
      "Thunder",
      "Glacier",
      "Tornado",
      "Forest",
      "Island",
      "Meteor",
      "Canyon",
      "Sunflower",
      "Iceberg",
      "Coral",
      "Cactus",
      "Waterfall",
      "Volcano",
      "Lightning",
      "Mushroom",
      "Avalanche",
      "Tide",
      "Comet",
      "Geyser",
    ],
  },
];
