// Built-in categorized words for Impostor. Plain data — add a category or more
// words by editing this list. Categories double as the optional impostor hint.
//
// Words are kept family-friendly and everyday: things a 10-year-old would
// recognise. British spellings throughout.

export interface WordCategory {
  category: string;
  words: string[];
}

export const WORD_BANK: WordCategory[] = [
  {
    category: "Food",
    words: [
      "Pizza",
      "Burger",
      "Hot dog",
      "Sandwich",
      "Spaghetti",
      "Noodles",
      "Rice",
      "Bread",
      "Toast",
      "Pancake",
      "Waffle",
      "Cereal",
      "Porridge",
      "Egg",
      "Bacon",
      "Sausage",
      "Chicken",
      "Fish fingers",
      "Chips",
      "Mashed potato",
      "Roast dinner",
      "Soup",
      "Salad",
      "Cheese",
      "Butter",
      "Jam",
      "Honey",
      "Peanut butter",
      "Yoghurt",
      "Ice cream",
      "Chocolate",
      "Sweets",
      "Lollipop",
      "Cake",
      "Cupcake",
      "Biscuit",
      "Cookie",
      "Doughnut",
      "Muffin",
      "Brownie",
      "Apple pie",
      "Jelly",
      "Custard",
      "Pudding",
      "Popcorn",
      "Crisps",
      "Pretzel",
      "Marshmallow",
      "Candy floss",
      "Apple",
      "Banana",
      "Orange",
      "Grapes",
      "Strawberry",
      "Raspberry",
      "Blueberry",
      "Watermelon",
      "Melon",
      "Pineapple",
      "Mango",
      "Peach",
      "Pear",
      "Cherry",
      "Lemon",
      "Lime",
      "Kiwi",
      "Coconut",
      "Carrot",
      "Potato",
      "Tomato",
      "Cucumber",
      "Lettuce",
      "Broccoli",
      "Peas",
      "Sweetcorn",
      "Beans",
      "Onion",
      "Mushroom",
      "Pumpkin",
      "Taco",
      "Burrito",
      "Nachos",
      "Sushi",
      "Dumpling",
      "Spring roll",
      "Curry",
      "Lasagne",
      "Meatball",
      "Kebab",
      "Wrap",
      "Bagel",
      "Croissant",
      "Garlic bread",
      "Fruit salad",
      "Milkshake",
      "Smoothie",
      "Lemonade",
      "Hot chocolate",
      "Juice",
      "Pancakes",
    ],
  },
  {
    category: "Animals",
    words: [
      "Dog",
      "Cat",
      "Rabbit",
      "Hamster",
      "Guinea pig",
      "Mouse",
      "Rat",
      "Horse",
      "Pony",
      "Donkey",
      "Cow",
      "Pig",
      "Sheep",
      "Goat",
      "Chicken",
      "Duck",
      "Goose",
      "Turkey",
      "Lion",
      "Tiger",
      "Leopard",
      "Cheetah",
      "Panther",
      "Bear",
      "Polar bear",
      "Panda",
      "Koala",
      "Kangaroo",
      "Elephant",
      "Giraffe",
      "Zebra",
      "Hippo",
      "Rhino",
      "Monkey",
      "Gorilla",
      "Chimpanzee",
      "Sloth",
      "Squirrel",
      "Hedgehog",
      "Fox",
      "Wolf",
      "Deer",
      "Badger",
      "Otter",
      "Beaver",
      "Raccoon",
      "Skunk",
      "Bat",
      "Mole",
      "Camel",
      "Llama",
      "Alpaca",
      "Snake",
      "Lizard",
      "Crocodile",
      "Alligator",
      "Turtle",
      "Tortoise",
      "Frog",
      "Toad",
      "Chameleon",
      "Gecko",
      "Iguana",
      "Dinosaur",
      "Shark",
      "Whale",
      "Dolphin",
      "Seal",
      "Walrus",
      "Octopus",
      "Squid",
      "Jellyfish",
      "Crab",
      "Lobster",
      "Starfish",
      "Seahorse",
      "Penguin",
      "Eagle",
      "Owl",
      "Parrot",
      "Flamingo",
      "Peacock",
      "Swan",
      "Robin",
      "Sparrow",
      "Pigeon",
      "Woodpecker",
      "Ostrich",
      "Bee",
      "Butterfly",
      "Ladybird",
      "Ant",
      "Spider",
      "Snail",
      "Worm",
      "Caterpillar",
      "Dragonfly",
      "Grasshopper",
      "Beetle",
      "Goldfish",
      "Reindeer",
    ],
  },
  {
    category: "Places",
    words: [
      "School",
      "Classroom",
      "Playground",
      "Park",
      "Garden",
      "Beach",
      "Sea",
      "Lake",
      "River",
      "Pond",
      "Forest",
      "Woods",
      "Jungle",
      "Desert",
      "Mountain",
      "Hill",
      "Cave",
      "Island",
      "Volcano",
      "Waterfall",
      "Farm",
      "Field",
      "Zoo",
      "Aquarium",
      "Safari park",
      "Museum",
      "Library",
      "Cinema",
      "Theatre",
      "Theme park",
      "Funfair",
      "Circus",
      "Stadium",
      "Swimming pool",
      "Gym",
      "Ice rink",
      "Bowling alley",
      "Trampoline park",
      "Soft play",
      "Hospital",
      "Dentist",
      "Police station",
      "Fire station",
      "Post office",
      "Bank",
      "Supermarket",
      "Shop",
      "Shopping centre",
      "Market",
      "Bakery",
      "Café",
      "Restaurant",
      "Toy shop",
      "Bookshop",
      "Pet shop",
      "Hairdresser",
      "Bus stop",
      "Train station",
      "Airport",
      "Harbour",
      "Lighthouse",
      "Castle",
      "Palace",
      "Church",
      "Bridge",
      "Tower",
      "Skyscraper",
      "Hotel",
      "Campsite",
      "Tent",
      "Treehouse",
      "Bedroom",
      "Kitchen",
      "Bathroom",
      "Living room",
      "Garage",
      "Attic",
      "Basement",
      "Shed",
      "Greenhouse",
      "Barn",
      "Stable",
      "Windmill",
      "Factory",
      "Office",
      "Car park",
      "Motorway",
      "Tunnel",
      "Cliff",
      "Valley",
      "Rainforest",
      "North Pole",
      "Space",
      "Moon",
      "Beach hut",
      "Pier",
      "Park bench",
      "Roundabout",
      "Crossroads",
      "Village",
    ],
  },
  {
    category: "Movies & Shows",
    words: [
      "Frozen",
      "Toy Story",
      "Cars",
      "Finding Nemo",
      "Finding Dory",
      "The Lion King",
      "Moana",
      "Encanto",
      "Coco",
      "Up",
      "Inside Out",
      "Brave",
      "Tangled",
      "Aladdin",
      "Beauty and the Beast",
      "Cinderella",
      "Snow White",
      "Sleeping Beauty",
      "The Little Mermaid",
      "Mulan",
      "Bambi",
      "Dumbo",
      "Peter Pan",
      "Pinocchio",
      "Zootropolis",
      "Big Hero 6",
      "Wreck-It Ralph",
      "Ratatouille",
      "Monsters Inc",
      "A Bug's Life",
      "The Incredibles",
      "Wall-E",
      "Soul",
      "Luca",
      "Turning Red",
      "Onward",
      "Sing",
      "Despicable Me",
      "Minions",
      "The Secret Life of Pets",
      "Shrek",
      "Madagascar",
      "Kung Fu Panda",
      "How to Train Your Dragon",
      "Trolls",
      "Puss in Boots",
      "Bee Movie",
      "The Lego Movie",
      "Spider-Man",
      "Batman",
      "Superman",
      "Wonder Woman",
      "The Avengers",
      "Iron Man",
      "Black Panther",
      "Sonic the Hedgehog",
      "Pokémon",
      "Detective Pikachu",
      "Jurassic Park",
      "Star Wars",
      "Harry Potter",
      "Paddington",
      "Wallace and Gromit",
      "Shaun the Sheep",
      "Chicken Run",
      "Matilda",
      "The Gruffalo",
      "Night at the Museum",
      "Home Alone",
      "The Goonies",
      "ET",
      "Jumanji",
      "Willy Wonka",
      "Mary Poppins",
      "The Wizard of Oz",
      "Annie",
      "Bluey",
      "Peppa Pig",
      "Paw Patrol",
      "SpongeBob SquarePants",
      "Scooby-Doo",
      "Tom and Jerry",
      "The Simpsons",
      "Horrid Henry",
      "Horrible Histories",
      "Teen Titans Go",
      "Gravity Falls",
      "Adventure Time",
      "The Amazing World of Gumball",
      "Phineas and Ferb",
      "Ben 10",
      "Pokémon Go",
      "LEGO Ninjago",
      "Sonic",
      "Mario",
      "The Smurfs",
      "Hotel Transylvania",
      "Cloudy with Meatballs",
      "The Croods",
      "Frozen 2",
    ],
  },
  {
    category: "Sports",
    words: [
      "Football",
      "Basketball",
      "Tennis",
      "Swimming",
      "Running",
      "Cycling",
      "Skiing",
      "Snowboarding",
      "Skateboarding",
      "Surfing",
      "Gymnastics",
      "Dancing",
      "Karate",
      "Judo",
      "Taekwondo",
      "Boxing",
      "Wrestling",
      "Golf",
      "Cricket",
      "Rugby",
      "Hockey",
      "Ice hockey",
      "Baseball",
      "Rounders",
      "Volleyball",
      "Badminton",
      "Table tennis",
      "Squash",
      "Bowling",
      "Archery",
      "Climbing",
      "Hiking",
      "Fishing",
      "Sailing",
      "Rowing",
      "Kayaking",
      "Canoeing",
      "Diving",
      "Horse riding",
      "Ice skating",
      "Roller skating",
      "Rollerblading",
      "Fencing",
      "Trampolining",
      "Cheerleading",
      "Netball",
      "Dodgeball",
      "Frisbee",
      "Darts",
      "Pool",
      "Snooker",
      "Sprinting",
      "Marathon",
      "Hurdles",
      "Long jump",
      "High jump",
      "Javelin",
      "Discus",
      "Shot put",
      "Pole vault",
      "Relay race",
      "Curling",
      "Bobsleigh",
      "Water polo",
      "Handball",
      "Lacrosse",
      "Polo",
      "Sumo wrestling",
      "Weightlifting",
      "Triathlon",
      "Skipping",
      "Hopscotch",
      "Tag",
      "Hide and seek",
      "BMX",
      "Motocross",
      "Go-karting",
      "Horse racing",
      "Show jumping",
      "Cross country",
      "Yoga",
      "Aerobics",
      "Beach volleyball",
      "Tug of war",
      "Egg and spoon race",
      "Sack race",
      "Three-legged race",
      "Conkers",
      "Marbles",
      "Sledging",
      "Paddleboarding",
      "Windsurfing",
      "Snorkelling",
      "Ballet",
      "Tap dancing",
      "Breakdancing",
      "Cartwheels",
      "Piggyback race",
      "Leapfrog",
    ],
  },
  {
    category: "Household",
    words: [
      "Table",
      "Chair",
      "Sofa",
      "Bed",
      "Pillow",
      "Blanket",
      "Duvet",
      "Wardrobe",
      "Drawer",
      "Cupboard",
      "Shelf",
      "Bookcase",
      "Desk",
      "Lamp",
      "Mirror",
      "Clock",
      "Picture",
      "Rug",
      "Carpet",
      "Curtains",
      "Window",
      "Door",
      "Stairs",
      "Television",
      "Remote",
      "Radio",
      "Speaker",
      "Phone",
      "Tablet",
      "Computer",
      "Laptop",
      "Keyboard",
      "Charger",
      "Camera",
      "Headphones",
      "Fridge",
      "Freezer",
      "Oven",
      "Cooker",
      "Microwave",
      "Toaster",
      "Kettle",
      "Blender",
      "Dishwasher",
      "Washing machine",
      "Tumble dryer",
      "Iron",
      "Hoover",
      "Broom",
      "Mop",
      "Bucket",
      "Dustpan",
      "Bin",
      "Plate",
      "Bowl",
      "Cup",
      "Mug",
      "Glass",
      "Fork",
      "Spoon",
      "Knife",
      "Saucepan",
      "Frying pan",
      "Spatula",
      "Whisk",
      "Chopping board",
      "Scissors",
      "Towel",
      "Toothbrush",
      "Toothpaste",
      "Soap",
      "Shampoo",
      "Sponge",
      "Toilet",
      "Sink",
      "Bath",
      "Shower",
      "Tap",
      "Plug",
      "Light switch",
      "Candle",
      "Torch",
      "Umbrella",
      "Keys",
      "Wallet",
      "Purse",
      "Bag",
      "Backpack",
      "Pencil",
      "Pen",
      "Rubber",
      "Ruler",
      "Glue",
      "Sellotape",
      "Stapler",
      "Notebook",
      "Calendar",
      "Cushion",
      "Doormat",
    ],
  },
  {
    category: "Jobs",
    words: [
      "Teacher",
      "Doctor",
      "Nurse",
      "Dentist",
      "Vet",
      "Firefighter",
      "Police officer",
      "Postman",
      "Bus driver",
      "Train driver",
      "Taxi driver",
      "Pilot",
      "Flight attendant",
      "Sailor",
      "Astronaut",
      "Soldier",
      "Chef",
      "Baker",
      "Butcher",
      "Waiter",
      "Farmer",
      "Fisherman",
      "Gardener",
      "Builder",
      "Carpenter",
      "Plumber",
      "Electrician",
      "Painter",
      "Mechanic",
      "Engineer",
      "Architect",
      "Scientist",
      "Inventor",
      "Artist",
      "Author",
      "Poet",
      "Musician",
      "Singer",
      "Drummer",
      "Guitarist",
      "Pianist",
      "Dancer",
      "Actor",
      "Director",
      "Magician",
      "Clown",
      "Acrobat",
      "Juggler",
      "Photographer",
      "Journalist",
      "Reporter",
      "Weather presenter",
      "Librarian",
      "Shopkeeper",
      "Cashier",
      "Hairdresser",
      "Barber",
      "Tailor",
      "Cleaner",
      "Caretaker",
      "Lifeguard",
      "Coach",
      "Referee",
      "Footballer",
      "Athlete",
      "Jockey",
      "Zookeeper",
      "Park ranger",
      "Lumberjack",
      "Miner",
      "Detective",
      "Spy",
      "Judge",
      "Lawyer",
      "Banker",
      "Accountant",
      "Receptionist",
      "Pharmacist",
      "Surgeon",
      "Optician",
      "Paramedic",
      "Beekeeper",
      "Shepherd",
      "Cowboy",
      "Knight",
      "King",
      "Queen",
      "Pirate",
      "Wizard",
      "Explorer",
      "Archaeologist",
      "President",
      "Bricklayer",
      "Window cleaner",
      "Tour guide",
      "DJ",
      "Newsreader",
      "Fortune teller",
      "Lollipop lady",
    ],
  },
  {
    category: "Nature",
    words: [
      "Sun",
      "Moon",
      "Star",
      "Sky",
      "Cloud",
      "Rain",
      "Rainbow",
      "Snow",
      "Snowflake",
      "Ice",
      "Frost",
      "Wind",
      "Storm",
      "Thunder",
      "Lightning",
      "Fog",
      "Mist",
      "Hail",
      "Sunshine",
      "Sunrise",
      "Sunset",
      "Tree",
      "Oak tree",
      "Leaf",
      "Branch",
      "Twig",
      "Root",
      "Bark",
      "Flower",
      "Rose",
      "Daisy",
      "Tulip",
      "Sunflower",
      "Daffodil",
      "Bluebell",
      "Dandelion",
      "Grass",
      "Bush",
      "Hedge",
      "Fern",
      "Moss",
      "Mushroom",
      "Toadstool",
      "Acorn",
      "Pinecone",
      "Berry",
      "Seed",
      "Cactus",
      "Vine",
      "Mountain",
      "Hill",
      "Valley",
      "Cliff",
      "Cave",
      "Rock",
      "Stone",
      "Pebble",
      "Boulder",
      "Sand",
      "Soil",
      "Mud",
      "Beach",
      "Ocean",
      "Wave",
      "Tide",
      "River",
      "Stream",
      "Lake",
      "Pond",
      "Puddle",
      "Waterfall",
      "Island",
      "Volcano",
      "Lava",
      "Earthquake",
      "Desert",
      "Forest",
      "Jungle",
      "Rainforest",
      "Meadow",
      "Field",
      "Swamp",
      "Glacier",
      "Iceberg",
      "Coral",
      "Seaweed",
      "Seashell",
      "Feather",
      "Spiderweb",
      "Nest",
      "Honeycomb",
      "Comet",
      "Planet",
      "Earth",
      "Galaxy",
      "Tornado",
      "Hurricane",
      "Spring",
      "Summer",
      "Autumn",
      "Winter",
    ],
  },
  {
    category: "Vehicles",
    words: [
      "Car",
      "Bus",
      "Lorry",
      "Truck",
      "Van",
      "Taxi",
      "Bike",
      "Motorbike",
      "Scooter",
      "Tricycle",
      "Unicycle",
      "Train",
      "Tram",
      "Underground",
      "Aeroplane",
      "Jet",
      "Helicopter",
      "Hot air balloon",
      "Glider",
      "Rocket",
      "Spaceship",
      "Boat",
      "Ship",
      "Yacht",
      "Sailboat",
      "Speedboat",
      "Canoe",
      "Kayak",
      "Rowing boat",
      "Dinghy",
      "Raft",
      "Submarine",
      "Ferry",
      "Cruise ship",
      "Hovercraft",
      "Jet ski",
      "Tractor",
      "Combine harvester",
      "Digger",
      "Bulldozer",
      "Excavator",
      "Crane",
      "Cement mixer",
      "Dumper truck",
      "Forklift",
      "Steamroller",
      "Fire engine",
      "Ambulance",
      "Police car",
      "Bin lorry",
      "Ice cream van",
      "Tow truck",
      "Tanker",
      "Removal van",
      "Caravan",
      "Camper van",
      "Motorhome",
      "Go-kart",
      "Quad bike",
      "Golf buggy",
      "Sledge",
      "Toboggan",
      "Sleigh",
      "Snowmobile",
      "Cable car",
      "Chairlift",
      "Gondola",
      "Rickshaw",
      "Carriage",
      "Cart",
      "Wheelbarrow",
      "Trolley",
      "Pram",
      "Pushchair",
      "Wheelchair",
      "Segway",
      "Jeep",
      "Limousine",
      "Sports car",
      "Racing car",
      "Monster truck",
      "Pickup truck",
      "Double-decker bus",
      "Coach",
      "Minibus",
      "School bus",
      "Steam train",
      "Bullet train",
      "Pirate ship",
      "Space shuttle",
      "Rollercoaster",
      "Big wheel",
      "Dodgems",
      "Skateboard",
      "Roller skates",
      "Stretcher",
      "Lifeboat",
      "Fishing boat",
      "Cruise liner",
    ],
  },
  {
    category: "Clothes",
    words: [
      "T-shirt",
      "Shirt",
      "Jumper",
      "Hoodie",
      "Cardigan",
      "Sweatshirt",
      "Vest",
      "Blouse",
      "Polo shirt",
      "Coat",
      "Jacket",
      "Raincoat",
      "Anorak",
      "Blazer",
      "Gilet",
      "Trousers",
      "Jeans",
      "Shorts",
      "Leggings",
      "Tracksuit",
      "Joggers",
      "Skirt",
      "Dress",
      "Pinafore",
      "Dungarees",
      "Onesie",
      "Pyjamas",
      "Nightie",
      "Dressing gown",
      "Swimsuit",
      "Swimming trunks",
      "Bikini",
      "Wetsuit",
      "Socks",
      "Tights",
      "Pants",
      "Knickers",
      "Shoes",
      "Trainers",
      "Boots",
      "Wellies",
      "Sandals",
      "Flip-flops",
      "Slippers",
      "High heels",
      "Plimsolls",
      "Football boots",
      "Hat",
      "Cap",
      "Beanie",
      "Bobble hat",
      "Sun hat",
      "Beret",
      "Helmet",
      "Crown",
      "Scarf",
      "Gloves",
      "Mittens",
      "Earmuffs",
      "Belt",
      "Braces",
      "Tie",
      "Bow tie",
      "Apron",
      "Overalls",
      "Uniform",
      "Costume",
      "Cape",
      "Glasses",
      "Sunglasses",
      "Goggles",
      "Watch",
      "Bracelet",
      "Necklace",
      "Earrings",
      "Ring",
      "Hairband",
      "Ribbon",
      "Handbag",
      "Backpack",
      "Rucksack",
      "Purse",
      "Wallet",
      "Shawl",
      "Poncho",
      "Kimono",
      "Kilt",
      "Waistcoat",
      "Bib",
      "Nappy",
      "Tutu",
      "Leotard",
      "Bobble",
      "Hairclip",
      "Headband",
      "Wristband",
      "Bandana",
      "Shoelaces",
    ],
  },
  {
    category: "School",
    words: [
      "Teacher",
      "Pupil",
      "Headteacher",
      "Classroom",
      "Desk",
      "Whiteboard",
      "Blackboard",
      "Chalk",
      "Board rubber",
      "Pen",
      "Pencil",
      "Pencil case",
      "Rubber",
      "Ruler",
      "Sharpener",
      "Crayon",
      "Felt tip",
      "Highlighter",
      "Marker",
      "Glue stick",
      "Scissors",
      "Stapler",
      "Paper clip",
      "Sellotape",
      "Notebook",
      "Exercise book",
      "Textbook",
      "Reading book",
      "Library",
      "Bookshelf",
      "School bag",
      "Lunchbox",
      "Water bottle",
      "Uniform",
      "School shoes",
      "Tie",
      "Blazer",
      "Register",
      "Homework",
      "Spelling test",
      "Exam",
      "Maths",
      "English",
      "Science",
      "History",
      "Geography",
      "Art",
      "Music",
      "PE",
      "Computing",
      "French",
      "Spanish",
      "Assembly",
      "Playtime",
      "Break",
      "Lunchtime",
      "Dinner lady",
      "Playground",
      "Field",
      "Hall",
      "Canteen",
      "Cloakroom",
      "Corridor",
      "Staffroom",
      "Reception",
      "Locker",
      "Bell",
      "Timetable",
      "Calculator",
      "Globe",
      "Map",
      "Atlas",
      "Dictionary",
      "Microscope",
      "Test tube",
      "Bunsen burner",
      "Easel",
      "Paintbrush",
      "Paint",
      "Clay",
      "Recorder",
      "Triangle",
      "Tambourine",
      "Skipping rope",
      "Hula hoop",
      "Bean bag",
      "Cone",
      "Whistle",
      "Sticker",
      "Gold star",
      "Report card",
      "Detention",
      "School trip",
      "Sports day",
      "Nativity play",
      "Wendy house",
      "Carpet time",
      "Show and tell",
      "Packed lunch",
    ],
  },
  {
    category: "Body",
    words: [
      "Head",
      "Hair",
      "Face",
      "Forehead",
      "Eye",
      "Eyebrow",
      "Eyelash",
      "Eyelid",
      "Nose",
      "Nostril",
      "Mouth",
      "Lip",
      "Tooth",
      "Tongue",
      "Gum",
      "Cheek",
      "Chin",
      "Jaw",
      "Ear",
      "Earlobe",
      "Neck",
      "Throat",
      "Shoulder",
      "Arm",
      "Elbow",
      "Wrist",
      "Hand",
      "Palm",
      "Finger",
      "Thumb",
      "Knuckle",
      "Fingernail",
      "Chest",
      "Tummy",
      "Belly button",
      "Back",
      "Spine",
      "Hip",
      "Bottom",
      "Leg",
      "Thigh",
      "Knee",
      "Shin",
      "Ankle",
      "Foot",
      "Heel",
      "Toe",
      "Toenail",
      "Sole",
      "Skin",
      "Muscle",
      "Bone",
      "Skeleton",
      "Skull",
      "Ribs",
      "Brain",
      "Heart",
      "Lungs",
      "Stomach",
      "Liver",
      "Kidney",
      "Blood",
      "Vein",
      "Nerve",
      "Joint",
      "Freckle",
      "Dimple",
      "Wrinkle",
      "Mole",
      "Scar",
      "Bruise",
      "Beard",
      "Moustache",
      "Pupil",
      "Iris",
      "Voice",
      "Breath",
      "Heartbeat",
      "Pulse",
      "Sneeze",
      "Cough",
      "Yawn",
      "Hiccup",
      "Burp",
      "Sweat",
      "Tear",
      "Smile",
      "Frown",
      "Wink",
      "Blink",
      "Nod",
      "Footprint",
      "Fingerprint",
      "Handprint",
      "Goosebumps",
      "Funny bone",
      "Calf",
      "Waist",
    ],
  },
  {
    category: "Toys & Games",
    words: [
      "Teddy bear",
      "Doll",
      "Dolls house",
      "Action figure",
      "Soft toy",
      "Rag doll",
      "Puppet",
      "Rocking horse",
      "Building blocks",
      "Wooden bricks",
      "Building set",
      "Jigsaw",
      "Train set",
      "Race track",
      "Toy car",
      "Toy lorry",
      "Toy tractor",
      "Toy aeroplane",
      "Toy boat",
      "Toy robot",
      "Toy dinosaur",
      "Toy farm",
      "Toy kitchen",
      "Tea set",
      "Marbles",
      "Spinning top",
      "Yo-yo",
      "Kite",
      "Frisbee",
      "Hula hoop",
      "Skipping rope",
      "Space hopper",
      "Pogo stick",
      "Bouncy ball",
      "Beach ball",
      "Bucket and spade",
      "Sandpit",
      "Swing",
      "Slide",
      "Seesaw",
      "Climbing frame",
      "Trampoline",
      "Scooter",
      "Roller skates",
      "Skateboard",
      "Tricycle",
      "Kaleidoscope",
      "Jack-in-the-box",
      "Wind-up toy",
      "Music box",
      "Bubbles",
      "Modelling clay",
      "Play dough",
      "Finger paint",
      "Colouring book",
      "Sticker book",
      "Crayons",
      "Felt tips",
      "Dressing-up box",
      "Costume",
      "Magic set",
      "Card trick",
      "Board game",
      "Noughts and crosses",
      "Snakes and ladders",
      "Draughts",
      "Chess",
      "Dominoes",
      "Dice",
      "Playing cards",
      "Tower blocks",
      "Conkers",
      "Hopscotch",
      "Hide and seek",
      "Tag",
      "Musical chairs",
      "Pass the parcel",
      "Blind man's buff",
      "Tug of war",
      "Sack race",
      "Egg and spoon",
      "Three-legged race",
      "Leapfrog",
      "Charades",
      "Treasure hunt",
      "Pillow fight",
      "Water pistol",
      "Water balloon",
      "Skittles",
      "Catch",
      "Whistle",
      "Rattle",
      "Toy drum",
      "Toy trumpet",
      "Stacking cups",
      "Shape sorter",
      "Marble run",
      "Snow globe",
      "Spinning wheel",
      "Paper aeroplane",
    ],
  },
  {
    category: "Drinks",
    words: [
      "Water",
      "Tap water",
      "Sparkling water",
      "Still water",
      "Bottled water",
      "Mineral water",
      "Iced water",
      "Lemon water",
      "Coconut water",
      "Milk",
      "Cold milk",
      "Warm milk",
      "Hot milk",
      "Strawberry milk",
      "Banana milk",
      "Chocolate milk",
      "Milkshake",
      "Strawberry milkshake",
      "Chocolate milkshake",
      "Banana milkshake",
      "Vanilla milkshake",
      "Smoothie",
      "Berry smoothie",
      "Banana smoothie",
      "Mango smoothie",
      "Green smoothie",
      "Orange juice",
      "Apple juice",
      "Pineapple juice",
      "Grape juice",
      "Cranberry juice",
      "Tomato juice",
      "Mango juice",
      "Tropical juice",
      "Fruit juice",
      "Squash",
      "Orange squash",
      "Blackcurrant squash",
      "Lemon squash",
      "Lime squash",
      "Cordial",
      "Elderflower cordial",
      "Lemonade",
      "Pink lemonade",
      "Cloudy lemonade",
      "Cherryade",
      "Limeade",
      "Orangeade",
      "Cola",
      "Cherry cola",
      "Fizzy drink",
      "Fizzy pop",
      "Cream soda",
      "Ginger beer",
      "Dandelion and burdock",
      "Tonic water",
      "Soda water",
      "Bitter lemon",
      "Iced tea",
      "Tea",
      "Milky tea",
      "Herbal tea",
      "Peppermint tea",
      "Camomile tea",
      "Fruit tea",
      "Green tea",
      "Hot chocolate",
      "Hot cocoa",
      "Drinking chocolate",
      "Malted milk",
      "Coffee",
      "Iced coffee",
      "Hot squash",
      "Barley water",
      "Lemon barley",
      "Honey and lemon",
      "Slushie",
      "Fruit punch",
      "Yoghurt drink",
      "Buttermilk",
      "Soya milk",
      "Oat milk",
      "Almond milk",
      "Coconut milk",
      "Rice milk",
      "Apple and blackcurrant",
      "Juice carton",
      "Hot blackcurrant",
      "Sports drink",
      "Energy drink",
      "Vegetable juice",
      "Carrot juice",
      "Beetroot juice",
      "Sparkling juice",
      "Berry juice",
      "Lemon and lime",
      "Refreshing drink",
      "Cold drink",
      "Bedtime milk",
    ],
  },
  {
    category: "Music",
    words: [
      "Guitar",
      "Drums",
      "Piano",
      "Violin",
      "Trumpet",
      "Recorder",
      "Microphone",
      "Singing",
      "Choir",
      "Band",
      "Headphones",
      "Whistle",
      "Triangle",
      "Tambourine",
      "Xylophone",
      "Flute",
      "Clarinet",
      "Saxophone",
      "Trombone",
      "Cello",
      "Double bass",
      "Harp",
      "Keyboard",
      "Organ",
      "Accordion",
      "Harmonica",
      "Bagpipes",
      "Banjo",
      "Ukulele",
      "Bongos",
      "Cymbals",
      "Maracas",
      "Castanets",
      "Cowbell",
      "Gong",
      "Bell",
      "Glockenspiel",
      "Kazoo",
      "Pan pipes",
      "French horn",
      "Tuba",
      "Oboe",
      "Bugle",
      "Drum kit",
      "Snare drum",
      "Bass drum",
      "Electric guitar",
      "Acoustic guitar",
      "Bass guitar",
      "Conductor",
      "Orchestra",
      "Concert",
      "Stage",
      "Melody",
      "Rhythm",
      "Beat",
      "Tune",
      "Song",
      "Lyrics",
      "Chorus",
      "Verse",
      "Note",
      "Chord",
      "Scale",
      "Sheet music",
      "Music stand",
      "Loud",
      "Quiet",
      "High note",
      "Low note",
      "Drummer",
      "Singer",
      "Guitarist",
      "Pianist",
      "Violinist",
      "Musician",
      "Pop music",
      "Rock music",
      "Classical music",
      "Jazz",
      "Rap",
      "Hip hop",
      "Folk music",
      "Country music",
      "Disco",
      "Dancing",
      "Clapping",
      "Humming",
      "Whistling",
      "Speaker",
      "Earphones",
      "Radio",
      "Volume",
      "Drumstick",
      "Strum",
      "Karaoke",
      "Busker",
      "Marching band",
    ],
  },
  {
    category: "Space",
    words: [
      "Sun",
      "Moon",
      "Star",
      "Planet",
      "Rocket",
      "Astronaut",
      "Comet",
      "Galaxy",
      "Spaceship",
      "Alien",
      "Satellite",
      "Telescope",
      "Asteroid",
      "Black hole",
      "Solar system",
      "Earth",
      "Mars",
      "Saturn",
      "Jupiter",
      "Venus",
      "Mercury",
      "Neptune",
      "Uranus",
      "Pluto",
      "Night sky",
      "Shooting star",
      "Meteor",
      "Meteorite",
      "Crater",
      "Orbit",
      "Gravity",
      "Universe",
      "Milky Way",
      "Constellation",
      "Spacesuit",
      "Space helmet",
      "Space station",
      "Space shuttle",
      "Launch pad",
      "Countdown",
      "Blast off",
      "Lift off",
      "Mission",
      "Rover",
      "Moon landing",
      "Moonwalk",
      "Crescent moon",
      "Full moon",
      "Half moon",
      "New moon",
      "Eclipse",
      "Solar eclipse",
      "Lunar eclipse",
      "Sunrise",
      "Sunset",
      "Sunlight",
      "Moonlight",
      "Starlight",
      "Twinkle",
      "Light year",
      "Rings of Saturn",
      "Red planet",
      "Big bang",
      "Outer space",
      "Deep space",
      "Zero gravity",
      "Weightless",
      "Floating",
      "Space rock",
      "Space dust",
      "Star cluster",
      "North Star",
      "Pole Star",
      "The Plough",
      "Great Bear",
      "Observatory",
      "Stargazing",
      "Space probe",
      "Spacewalk",
      "Capsule",
      "Booster",
      "Fuel tank",
      "Mission control",
      "Space race",
      "Crew",
      "Cosmos",
      "Nebula",
      "Supernova",
      "Solar wind",
      "Sunspot",
      "Atmosphere",
      "Spaceport",
      "Space helmet visor",
      "Moon buggy",
      "Flying saucer",
      "Cosmonaut",
      "Starship",
      "Meteor shower",
      "Telescope lens",
      "Space junk",
    ],
  },
];
