// Family-friendly "Would you rather" dilemmas. Read aloud; everyone says which
// they'd pick and why. Kept silly and kid-appropriate.

export const WOULD_YOU_RATHER: string[] = [
  "Would you rather be able to fly or be invisible?",
  "Would you rather have a pet dragon or a pet dinosaur?",
  "Would you rather be able to talk to animals or speak every language?",
  "Would you rather live in a treehouse or a castle?",
  "Would you rather have super strength or super speed?",
  "Would you rather eat pizza every day or ice cream every day?",
  "Would you rather be a famous singer or a famous footballer?",
  "Would you rather never have to sleep or never have to eat?",
  "Would you rather breathe underwater or walk through walls?",
  "Would you rather have a tail or wings?",
  "Would you rather be the size of a mouse or the size of an elephant?",
  "Would you rather always be too hot or always be too cold?",
  "Would you rather have a robot that does your homework or a robot that tidies your room?",
  "Would you rather visit space or the bottom of the ocean?",
  "Would you rather be able to freeze time or rewind time?",
  "Would you rather have hands for feet or feet for hands?",
  "Would you rather only be able to whisper or only be able to shout?",
  "Would you rather live where it's always summer or always winter?",
  "Would you rather have a magic carpet or a magic broomstick?",
  "Would you rather be a wizard or a superhero?",
  "Would you rather have unlimited sweets or unlimited toys?",
  "Would you rather be able to teleport or read minds?",
  "Would you rather have a slide instead of stairs or a pool instead of a garden?",
  "Would you rather be best friends with a unicorn or a talking cat?",
  "Would you rather always have to skip everywhere or always have to hop?",
  "Would you rather have spaghetti for hair or cheese for skin?",
  "Would you rather meet a real-life dinosaur or a real-life alien?",
  "Would you rather have a bedroom full of balloons or full of bouncy balls?",
  "Would you rather be able to paint with your mind or sing perfectly?",
  "Would you rather never lose at video games or never lose at sport?",
  "Would you rather have a chocolate fountain or a lemonade fountain at home?",
  "Would you rather ride a giant tortoise or a giant eagle to school?",
  "Would you rather sneeze glitter or burp bubbles?",
  "Would you rather have a personal theme park or a personal zoo?",
  "Would you rather be able to grow plants instantly or talk to trees?",
  "Would you rather have shoes that bounce or shoes that fly?",
  "Would you rather always know what's for dinner or always know what the weather will be?",
  "Would you rather be a knight or a pirate?",
  "Would you rather have a snowball fight or a water balloon fight?",
  "Would you rather have a robot best friend or a dinosaur best friend?",
  "Would you rather be able to jump really high or run really fast?",
  "Would you rather have a magic pencil that draws real things or a magic book that reads itself?",
  "Would you rather live on a boat or in a hot air balloon?",
  "Would you rather have a giraffe neck or elephant ears?",
  "Would you rather only eat sweet food or only eat salty food?",
  "Would you rather have a invisible cloak or a time machine?",
  "Would you rather always wear a fancy costume or always wear pyjamas?",
  "Would you rather control the weather or control the seasons?",
  "Would you rather have a hamster the size of a horse or a horse the size of a hamster?",
  "Would you rather be the funniest or the cleverest person in the room?",
  "Would you rather have hiccups for a whole year or always sneeze glitter?",
  "Would you rather grow a tail you can wag or ears that hear everything?",
  "Would you rather have feet made of marshmallow or hands made of rubber?",
  "Would you rather sleep on a giant lily pad or inside a cosy acorn?",
  "Would you rather have a button that pauses your sister or your brother?",
  "Would you rather have a bubble that follows you or a tiny cloud overhead?",
  "Would you rather slide down a rainbow or bounce on a giant jelly?",
  "Would you rather have a backpack that's bottomless or shoes that never wear out?",
  "Would you rather eat dinner for breakfast or pudding for every meal?",
  "Would you rather hop everywhere like a frog or roll everywhere like a ball?",
  "Would you rather have a garden full of sweets or a pond full of fizzy drink?",
  "Would you rather wear a hat that tells jokes or shoes that play music?",
  "Would you rather have a pet fluffy llama or a tiny hedgehog?",
  "Would you rather laugh like a hyena or honk like a goose when happy?",
  "Would you rather have a duvet made of clouds or a pillow made of feathers?",
  "Would you rather paint with your fingers or draw with your toes?",
  "Would you rather grow flowers from your hair or leaves from your fingertips?",
  "Would you rather have a desk that's a trampoline or a chair that spins forever?",
  "Would you rather turn into a balloon or turn into a beach ball?",
  "Would you rather have a tongue that tastes colours or eyes that see sounds?",
  "Would you rather live in a giant boot or a giant teapot?",
  "Would you rather have a snowball fight in summer or a water fight in winter?",
  "Would you rather have a key that opens any door or a map that shows any place?",
  "Would you rather wear roller skates all day or stilts all day?",
  "Would you rather have a milkshake river or a chocolate waterfall?",
  "Would you rather sneeze bubbles or burp confetti?",
  "Would you rather have a bike that flies low or a scooter that swims?",
  "Would you rather have a pet cloud that rains lemonade or one that snows candyfloss?",
  "Would you rather wear a cape that glows or boots that leave glittery footprints?",
  "Would you rather have a fork that twirls itself or a spoon that scoops on its own?",
  "Would you rather have a snail's slow day or a squirrel's busy day?",
  "Would you rather have a garden gnome that talks or a scarecrow that dances?",
  "Would you rather have a trampoline floor or a bouncy castle bedroom?",
  "Would you rather have hair that changes colour daily or nails that glow at night?",
  "Would you rather always smell of fresh bread or fresh strawberries?",
  "Would you rather have a magic pencil that draws real food or real toys?",
  "Would you rather have a swimming pool of custard or a bath of bubbles forever?",
  "Would you rather be best mates with a friendly yeti or a cheeky goblin?",
  "Would you rather have a kite that pulls you along or a sledge that goes uphill?",
  "Would you rather have wellies that never get muddy or a coat that's always warm?",
  "Would you rather have a snowman that never melts or a sandcastle that never crumbles?",
  "Would you rather have a piano that plays itself or a drum that keeps the beat?",
  "Would you rather have a giant slide in the garden or a maze in the house?",
  "Would you rather have a robot pet parrot or a robot pet tortoise?",
  "Would you rather hop into any storybook or any cartoon for a day?",
  "Would you rather have a torch that shows treasure or a compass that finds biscuits?",
  "Would you rather have a window that shows any view or a door to a secret room?",
  "Would you rather have a wardrobe that picks your outfit or a kitchen that cooks alone?",
  "Would you rather have a pet jellyfish that glows or a pet firefly in a jar?",
  "Would you rather be brilliant at juggling or brilliant at cartwheels?",
  "Would you rather have a bedroom on a hilltop or a bedroom in a big tree?",
  "Would you rather have a snack that refills itself or a drink that never runs out?",
  "Would you rather have a friendly ghost who tidies up or a pixie who hides your socks?",
  "Would you rather make it rain glitter or make it snow popcorn?",
  "Would you rather have a pet that purrs songs or one that barks in tune?",
  "Would you rather have shoes that skip for you or gloves that wave for you?",
  "Would you rather have a pancake hat or a waffle umbrella?",
  "Would you rather have a swing that reaches the clouds or a seesaw that never stops?",
  "Would you rather have a magic crayon or a magic eraser?",
  "Would you rather have a tree that grows lollies or a bush that grows marshmallows?",
  "Would you rather have a hat full of pigeons or pockets full of butterflies?",
  "Would you rather have a school day on a boat or a school day on a train?",
  "Would you rather have a snowy garden all year or a sunny garden all year?",
];
